### ISSUE TITLE
Multiline comments cause error in parsing

### ISSUE THREAD

**Issue by skyrod-vactai** [bowbahdoe/edn-format#1]
This parses ok:
```clj
;; foo
 ;; bar
```
this doesn't:
```clj
;; foo
;; bar
```
The only difference is that in the first example, there's a space before the first semicolon on the 2nd line. Without that whitespace, the parser errors with `Err(ParserErrorWithContext { context: [], row: 1, col: 2, error: UnexpectedCharacter(';') })`

I looked at the unit tests and they don't cover this, the comment tests all have whitespace.

Here's a tiny reproducer:
```rust
extern crate edn_format;

fn main() {
    println!("{:?}", edn_format::parse_str(";; abc\n;; def \n\n ced"));
}
```

**Comment by bowbahdoe** [comment]
Taking a look now

**Comment by bowbahdoe** [comment]
@skyrod-vactai This should be fixed now in 3.2.3. Let me know if you run into anything else + what you are using the library for (genuinely curious)

**Comment by skyrod-vactai** [comment]
I'm developing a simple programming language (closely related to Joy). Its source code (and data, it's homoiconic) is a subset of edn (vectors, boolean, string, numbers, symbols, and one reader tag for base64 encoded bytes). I'm using your lib as the reader/writer. Thanks for making the lib and being so responsive to my bug report. I'm about to upgrade and try out the fix.

**Comment by skyrod-vactai** [comment]
Fixed! Thanks!

**Comment by bowbahdoe** [comment]
@skyrod-vactai As far as i am aware you are my only user, so if you have any issues/questions/feature requests or just want a rubber duck feel free to message me on whatever platform
